site_name: beezy.cloud
site_url: https://docs.beezy.cloud
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  palette: 
    - scheme: slate
      primary: red 
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/beezy-cloud/website
  generator: false
copyright: Copyright &copy; 2022 beezy.cloud - Licensed under the Apache-2.0 License
repo_url: https://github.com/beezy-cloud/website
repo_name: beezy-cloud/website

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Introduction: 'index.md'
  - Breakdown: 'breakdown.md'
  - Environment: 'environment.md'
  - Sections: 
    - The Operator Menace: 'operatormenace.md'
    - The Automation Strike Back: 'automationstrikeback.md'
    - The Return of Observability: 'returnoftheobservability.md'
    - The DevSecOps Awakens: 'devsecopsawakens.md'
