site_name: beez.cloud
site_url: https://docs.beezy.cloud
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/beezy-cloud/website
  generator: false
copyright: Copyright &copy; 2022 beezy.cloud - Licensed under the Apache-2.0 License
repo_url: https://github.com/beezy-cloud/website
repo_name: beezy-cloud/website

markdown_extensions:
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Introduction: 'index.md'
  - Articles: 
    - The Operator Meance: 'operatormenace.md'
    - The Automation Strike Back: 'automationstrikeback.md'
    - The Returns of Observability: 'returnoftheobservability.md'
    - The DevSecOps Awakens: 'devsecopsawaken.md'
